sudo: false
language: node_js
node_js:
 - "node"
cache:
  directories:
  - node_modules
before_install:
  - npm i -g codecov.io
  - npm i -g codecov
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run coverage
after_success:
  - npm run report-coverage